version: "3.8"

services:
  ngnix:
    depends_on:
      - lnchecker
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    network_mode: "host"
    restart: on-failure
  lnchecker:
    build: .
    restart: on-failure
    network_mode: "host"
    environment:
      - NEXT_PUBLIC_REST_URL=http://52.55.124.1:7000
